// Category durability
window.categoryDurability = {
  "Bra":        { maxUses: 60,  maxWashes: 40,  maxYears: 1.5 },
  "Panties":    { maxUses: 50,  maxWashes: 30,  maxYears: 1   },

  "T-shirt":    { maxUses: 100, maxWashes: 50,  maxYears: 2   },
  "Shirt":      { maxUses: 120, maxWashes: 60,  maxYears: 3   },
  "Jeans":      { maxUses: 200, maxWashes: 100, maxYears: 5   },
  "Pants":      { maxUses: 200, maxWashes: 100, maxYears: 4   },
  "Shorts":     { maxUses: 120, maxWashes: 60,  maxYears: 3   },
  "Skirt":      { maxUses: 120, maxWashes: 60,  maxYears: 3   },
  "Dress":      { maxUses: 100, maxWashes: 50,  maxYears: 2   },
  "Sweater":    { maxUses: 150, maxWashes: 75,  maxYears: 3   },
  "Hoodie":     { maxUses: 200, maxWashes: 90,  maxYears: 4   },
  "Jacket":     { maxUses: 300, maxWashes: 150, maxYears: 10  },
  "Coat":       { maxUses: 400, maxWashes: 80,  maxYears: 10  },
  "Socks":      { maxUses: 50,  maxWashes: 40,  maxYears: 1   },
  "Shoes":      { maxUses: 500, maxWashes: 0,   maxYears: 8   },
  "Hat":        { maxUses: 100, maxWashes: 20,  maxYears: 3   },
  "Casual":     { maxUses: 150, maxWashes: 70,  maxYears: 3   },
  "Formal":     { maxUses: 80,  maxWashes: 40,  maxYears: 2   },
  "Athletic":   { maxUses: 250, maxWashes: 100, maxYears: 3   },
  "Other":      { maxUses: 100, maxWashes: 50,  maxYears: 2   },
};

// Fabric durability multipliers
window.fabricDurability = {
  "Cotton":    { durabilityMultiplier: 1.0 },
  "Polyester": { durabilityMultiplier: 1.2 },
  "Wool":      { durabilityMultiplier: 0.8 },
  "Leather":   { durabilityMultiplier: 2.0 },
  "Silk":      { durabilityMultiplier: 0.7 },
  "Nylon":     { durabilityMultiplier: 1.3 },
  "Linen":     { durabilityMultiplier: 1.0 },
  "Acrylic":   { durabilityMultiplier: 0.9 },
  "Spandex":   { durabilityMultiplier: 1.5 },
  "Cashmere":  { durabilityMultiplier: 0.6 },
  "Bamboo":    { durabilityMultiplier: 1.1 },
  "Denim":     { durabilityMultiplier: 1.2 },
  "Rayon":     { durabilityMultiplier: 0.9 },
  "Viscose":   { durabilityMultiplier: 0.95 },
  "Modal":     { durabilityMultiplier: 1.0 },
  "Organza":   { durabilityMultiplier: 0.85 },
  "Velvet":    { durabilityMultiplier: 0.8 },
  "Satin":     { durabilityMultiplier: 0.8 },
  "Lyocell":   { durabilityMultiplier: 1.05 },
  "Chiffon":   { durabilityMultiplier: 0.75 },
  "Latex":     { durabilityMultiplier: 1.3 },
};
